###
POST http://localhost:8000/api/v1/admin
Content-Type: application/json

{
    "fName":"Roshan",
    "lName":"Lama",
    "email":"roshan2@gmail.com",
    "password":"234234234"
}

###
POST http://localhost:8000/api/v1/admin/login
Content-Type: application/json

{ 
    "email":"roshan2@gmail.com",
    "password":"234234234"
}